export const allBook = [
  {
    id: 1,
    img: "/book-item-1.jpg",
    title: "Giáo Trình Kỹ Thuật Lập Trình C Căn Bản Và Nâng Cao",
    author: "Nhiều tác giả",
    price: "150.000đ",
    onSale: "30%",
    priceOnSale: "30.000đ",
    marketPrice: "180.000đ",
    rate: "⭐⭐⭐⭐⭐",
    comment: "(5 nhận xét)",
    link: "https://tiki.vn/giao-trinh-ky-thuat-lap-trinh-c-can-ban-va-nang-cao-p1664525.html?src=search&2hi=1&keyword=lap%20trinh&_lc=Vk4wMzkwMTEwMTI%3D",
    done: false,
  },
  {
    id: 2,
    img: "/book-item-2.jpg",
    title: "Sách Lập trình với Scratch 3.0",
    author: "Nguyễn Hữu Hưng (chủ biên)",
    price: "200.000đ",
    onSale: "5%",
    priceOnSale: "20.000đ",
    marketPrice: "220.000đ",
    rate: "⭐⭐⭐⭐",
    comment: "(0 nhận xét)",
    link: "https://tiki.vn/lap-trinh-voi-scratch-p570011.html?_v=new&utm_expid=.DBaJF6tGT8q4Pf7eIheFWQ.1&utm_referrer=https%3A%2F%2Fwww.google.com%2F",
    done: false,
  },
  {
    id: 3,
    img: "/book-item-3.jpg",
    title: "Học lập trình frontend nâng cao",
    author: "Không biết",
    price: "199.000đ",
    onSale: "29%",
    priceOnSale: "81.000đ",
    marketPrice: "280.000đ",
    rate: "⭐⭐⭐",
    comment: "(2 nhận xét)",
    link: "https://tiki.vn/hoc-lap-trinh-frontend-nang-cao-p21268387.html?_v=new&src=search&2hi=0&keyword=lap%20trinh%20vuejs&_lc=Vk4wMzkwMTEwMTI%3D&utm_expid=.DBaJF6tGT8q4Pf7eIheFWQ.1&utm_referrer=https%3A%2F%2Ftiki.vn%2Fsearch%3Fq%3Dlap%2Btrinh%2Bvuejs%26_lc%3DVk4wMzkwMTEwMTI%253D",
    done: false,
  },
  {
    id: 4,
    img: "/book-item-4.jpg",
    title: "Học lập trình frontend nâng cao với React JS",
    author: "Không biết",
    price: "199.000đ",
    onSale: "29%",
    priceOnSale: "81.000đ",
    marketPrice: "280.000đ",
    rate: "⭐⭐⭐⭐",
    comment: "(6 nhận xét)",
    link: "https://tiki.vn/hoc-lap-trinh-frontend-nang-cao-voi-react-js-p20351205.html?src=search&2hi=0&keyword=H%E1%BB%8Dc%20l%E1%BA%ADp%20tr%C3%ACnh%20frontend%20n%C3%A2ng%20cao&_lc=Vk4wMzkwMTEwMTI%3D",
    done: false,
  },
];
